export const provinceMap = {
  Bali: "1",
  "Bangka Belitung": "2",
  Banten: "3",
  Bengkulu: "4",
  "DI Yogyakarta": "5",
  "DKI Jakarta": "6",
  Gorontalo: "7",
  Jambi: "8",
  "Jawa Barat": "9",
  "Jawa Tengah": "10",
  "Jawa Timur": "11",
  "Kalimantan Barat": "12",
  "Kalimantan Selatan": "13",
  "Kalimantan Tengah": "14",
  "Kalimantan Timur": "15",
  "Kalimantan Utara": "16",
  "Kepulauan Riau": "17",
  Lampung: "18",
  Maluku: "19",
  "Maluku Utara": "20",
  "Nanggroe Aceh Darussalam (NAD)": "21",
  "Nusa Tenggara Barat (NTB)": "22",
  "Nusa Tenggara Timur (NTT)": "23",
  Papua: "24",
  "Papua Barat": "25",
  Riau: "26",
  "Sulawesi Barat": "27",
  "Sulawesi Selatan": "28",
  "Sulawesi Tengah": "29",
  "Sulawesi Tenggara": "30",
  "Sulawesi Utara": "31",
  "Sumatera Barat": "32",
  "Sumatera Selatan": "33",
  "Sumatera Utara": "34",
};
